influxdb:
    build: ./
    mem_limit: 4g
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    labels:
      - triton.cns.services=influxdb
    links:
      - consul:consul
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - LOG_LEVEL=debug
      - CONSUL=consul
consul:
    image: autopilotpattern/consul
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap
        -bootstrap-expect 0
        -config-dir=/etc/consul
        -ui-dir /ui
        -client "0.0.0.0"
    restart: always
    mem_limit: 128m
    ports:
      - "8500:8500"
    expose:
      - "53"
      - "8300-8302"
      - "8400"
    dns:
      - 127.0.0.1
    labels:
      - triton.cns.services=consul
