version: '2.1'
services:
    influxdb:
        build: ./
        restart: always
        ports:
          - "8083:8083"
          - "8086:8086"
        environment:
          - CONSUL=consul
          - INFLUXDB_ADMIN_ENABLED=true
          - LOG_LEVEL=debug

    consul:
        image: autopilotpattern/consul:0.7.2-r0.8
        command: >
          /usr/local/bin/containerpilot
          /bin/consul agent -server
            -bootstrap
            -config-dir=/etc/consul
            -ui-dir /ui
            -client=0.0.0.0
        restart: always
        ports:
          - "8500:8500"
